[package]
name = "check"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]

[dependencies]
log = "0.3.6"
env_logger = "0.3.3"
union-find = "0.3.1"

[dependencies.base]
path = "../base"

[dependencies.parser]
path = "../parser"
optional = true

[features]
test = ["parser"]
