[package]
name = "check"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]

[dependencies.log]
[dependencies.env_logger]

[dependencies.union-find]
git = "https://github.com/Marwes/union-find-rs"

[dependencies.base]
path = "../base"
[dependencies.parser]
path = "../parser"

