[package]
name = "gluon_format"
version = "0.7.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Code formatting for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.4"
pretty = "0.3.2"
itertools = "0.7.0"

gluon_base = { path = "../base", version = "0.7.1" } # GLUON
gluon = { path = "..", version = "0.7.1" } # GLUON

[dev-dependencies]
env_logger = "0.5.0"
difference = "1.0"
pretty_assertions = "0.4"

[features]
test = []
