language: rust
sudo: false
cache: cargo
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly
- beta
- stable
os:
- linux
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
script:
- |
  sh ./test-no-skeptic.sh &&
  travis-cargo --only nightly test -- --features "test nightly" -p gluon compile_test &&
  cargo build --release &&
  cargo build --release -p gluon_repl &&
  travis-cargo --only nightly bench &&
  cargo build --all --no-default-features
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/78796507a78a48a4b18e
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: releases
  api_key:
    secure: ImhF+DkxyHyzDQ4SZZlATjgkrzr+yY1xwADxgO2B5Xi+C7AOllkPInSB/RL+C6tebQnxIEop7KU0N4svbIw6zuoDmOvkliP++U1gXDqvpggBT7AXM5ICcLKWUzTdh3XexhL5SUmtH+QvWRwFwcOoq6mic8rc6DSvTojB/NydyJCeHGvx5iSl5o/ZSqrnEjOF/yDMXADVNwQRZebzyXss+wtTfEbD7OZoJ9ihPugDES8EkmScwS/UCJfCfEqBf/AwDSaAxVpPB/2PF7J0bDIB1ORrwA4HUguJ/U5QuV4vea0hNhhIzzwfcsbPhPLARcLENZLirUk3iygbwSPCTNg+8yEz0MPJQVTj/T48cbKkn9rgZfWi3Bs9nyv22ZouKBFQooiQD6b7WhVGY8bA1Q39cTSLfrR9WrkiRS3x11QrNkwWUqvWHb+2u0KtovTnCt9Lxrx0j8WKMO5Onx6hLfGfH00puCNpV8keWqkzriSi7/ce4mBl8HTvFX22bKZ5uZAxX2mPodAtWoh8hgOGMZhjG2ODS1CEQBxWw5nCXkKQE1afaJOEjhzXmmSNzTnfWIFQGk6V9T9LF8u/PrSVmkQCgka/arlUQlKl+Fa8XUEx8DZEHptj2OdP86A2qiUOcsAmYF2z19kYziHYK3Ll1xDPoOSil6Eej5t+n/e37bmvTMY=
  file: target/release/gluon
  skip_cleanup: true
  on:
    rust: stable
    tags: true
    repo: gluon-lang/gluon
