language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  sh ./test-no-skeptic.sh &&
  travis-cargo --only nightly test -- --features "test nightly" -p gluon compile_test &&
  travis-cargo --only stable test -- --features "test skeptic" -p gluon --test skeptic-tests &&
  cargo build --release &&
  travis-cargo --only nightly bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
  - secure: K26ZRkSrB2i9bUXgpIoMnKpgC1kItXDyvkIi1iRQE4aZxDOi7K43vO46heDcRrqVj+G5TLF3CTCS4eU7NW13tF2uh3a+r1Z8X1ZJuoVEnIAkMPQMm4GCnsRZUB23rBiNY1MB7CFCA8VhbLRCCgvr+OJZshb58XNZh2QSRGUY6MKbAAn11gCWvV7fl7CU0S65IveOxGQZLG8Rycb593hW8Vl1OEjYe8PD9yUz6kotIsiWqOcIWLF1bljoJFbTZMq07gp4n80wcx7OpeCFxHe9z0SOR81m3Jic2rHrvFNt72+lG7Exz6MavwHPENtotZ/81rvcg9F5dM0UJ6vaqnSbemXxQ8FGkuZImkIAbkyaKf8xwMx2++6mg76Sn8Y/dB4wc3PZlBE19834Zrtocp0t+vAmFmx/LDhJl5+sj3/vm+wbp317DVuQQCNeBqQoNarYxl/OpgNsbMhIYRDcK2SIPRp37E4PgYbW1/ilMNg46qis3O9tairjO6yJ7oep9OjNcDs8IQwUc9G47N63Xwpm6vhWPeCdC4LnRD+0eXce4C37W4q4CTSM5oYi7+hxV0vEGLWNV/YZdmaJpFoysJ774eIKevyOBRsSLqCMClU/rCVlJsFOzBLjYOaI6YARGDpHjcL2LbfNIBDSwe0yg5WkoIAA0EibPhDU9vedPSYFt5A=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1f97acdae0f19676b03b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
