language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly
- beta
- stable
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    rust: nightly
  - os: osx
    rust: beta
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
script:
- |
  sh ./test-no-skeptic.sh &&
  travis-cargo --only nightly test -- --features "test nightly" -p gluon compile_test &&
  cargo build --release &&
  travis-cargo --only nightly bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
  - secure: K26ZRkSrB2i9bUXgpIoMnKpgC1kItXDyvkIi1iRQE4aZxDOi7K43vO46heDcRrqVj+G5TLF3CTCS4eU7NW13tF2uh3a+r1Z8X1ZJuoVEnIAkMPQMm4GCnsRZUB23rBiNY1MB7CFCA8VhbLRCCgvr+OJZshb58XNZh2QSRGUY6MKbAAn11gCWvV7fl7CU0S65IveOxGQZLG8Rycb593hW8Vl1OEjYe8PD9yUz6kotIsiWqOcIWLF1bljoJFbTZMq07gp4n80wcx7OpeCFxHe9z0SOR81m3Jic2rHrvFNt72+lG7Exz6MavwHPENtotZ/81rvcg9F5dM0UJ6vaqnSbemXxQ8FGkuZImkIAbkyaKf8xwMx2++6mg76Sn8Y/dB4wc3PZlBE19834Zrtocp0t+vAmFmx/LDhJl5+sj3/vm+wbp317DVuQQCNeBqQoNarYxl/OpgNsbMhIYRDcK2SIPRp37E4PgYbW1/ilMNg46qis3O9tairjO6yJ7oep9OjNcDs8IQwUc9G47N63Xwpm6vhWPeCdC4LnRD+0eXce4C37W4q4CTSM5oYi7+hxV0vEGLWNV/YZdmaJpFoysJ774eIKevyOBRsSLqCMClU/rCVlJsFOzBLjYOaI6YARGDpHjcL2LbfNIBDSwe0yg5WkoIAA0EibPhDU9vedPSYFt5A=
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/78796507a78a48a4b18e
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: releases
  api_key:
    secure: F86FGNVU2PbDun/ek45DX7EB0g6pyoZkaolVKa+K8ZE/x5FJZ/fBv7YtnhMSk5JcZs2vUtI0NDuHlSZwkkXj5ozu0vpp2ohDedALWKsxA68nf3iOkeT4SFUD5EMko9+G9z7fThWJPmE1LShtDEmlhLVXZ9dWZC0II9ojCAfxJmpaU0OruwF6FBvF26VYMgmCzJagyNdWt0GmG9HjyUgxC0exPajWzrg67/sUf7hVxuB/QC9csHwXMR+E31yMeiZNOUUh01z6D+ZQX4XmmuaB8yXeK3MirSoRR2AT3hSwfgEVsprSjVkRqCdouK13wjVmPYV9zS8gX+pwAvfjUR2hw/6MR1E3a16h4v5bpLil/qo65m2bhVXzGirx20uSIUuBRekuOpvEr1/0HjhdGLFq1RwDdLtOJVAryN4OLbJMtKmoJDAtvPg3eQqklsHHtxVIxkqRx/r7KhhcECjwSQhPvtIclc2Lk+yJaCk7Gw+DH27H0EYcHAnCf2py9JreTqy5DQy6UYeSEt+xo9cI1BDPQo6uhbQ5GkKV2nu98OFuI21F9u2IM3WnwrOgLIqFDpOhQeIXYbEx6AjahwBMGOseG/6X7FFytl2HeXTeFV8ey3paSM/dCadbYT9DaO5NiPtdUBEYnkH6f8IQug+71TAyknap7G3p+fleH+87WUHxSYI=
  file: target/release/repl
  on:
    repo: gluon-lang/gluon
