[package]

name = "embed_lang"
version = "0.0.1"
authors = ["Markus <marwes91@gmail.com>"]


[lib]

name = "embed_lang"
path = "src/lib.rs"


[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
log = "0.3.6"
env_logger = "0.3.3"
clap = "2.2.5"
quick-error = "1.0.0"

[dependencies.base]
path = "base"
[dependencies.parser]
path = "parser"
[dependencies.check]
path = "check"
[dependencies.vm]
path = "vm"

[features]
test = ["check/test", "parser/test"]
