[package]

name = "gluon"
version = "0.0.1"
authors = ["Markus <marwes91@gmail.com>"]
build = "build.rs"

[lib]

name = "gluon"
path = "src/lib.rs"


[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
log = "0.3.6"
clap = "2.2.5"
quick-error = "1.0.0"

[dependencies.base]
path = "base"
[dependencies.parser]
path = "parser"
[dependencies.check]
path = "check"
[dependencies.vm]
path = "vm"

[dependencies.compiletest_rs]
version = "0.1.3"
optional = true

[dependencies.env_logger]
version = "0.3.3"
optional = true

[dependencies.linenoise-rust]
version = "0.2.0"
optional = true

[dependencies.lazy_static]
version = "0.2.0"
optional = true

[build-dependencies]
skeptic = "0.4"

[dev-dependencies]
skeptic = "0.4"

[features]
default = ["repl"]

repl = ["env_logger", "lazy_static", "linenoise-rust"]
test = ["vm/test", "check/test", "parser/test", "repl"]
nightly = ["compiletest_rs"]
test_nightly = ["test", "nightly"]
