[package]

name = "gluon"
version = "0.1.3"
authors = ["Markus <marwes91@gmail.com>"]
build = "build.rs"

license = "MIT"

description = "A static, type inferred programming langauge for application embedding"

repository = "https://github.com/Marwes/gluon"
documentation = "https://marwes.github.io/gluon/gluon/index.html"
readme = "README.md"

[lib]

name = "gluon"
path = "src/lib.rs"

[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
log = "0.3.6"
clap = "2.2.5"
quick-error = "1.0.0"

[dependencies.gluon_base]
path = "base"
version = "0.1.3"

[dependencies.gluon_parser]
path = "parser"
version = "0.1.2"

[dependencies.gluon_check]
path = "check"
version = "0.1.3"

[dependencies.gluon_vm]
path = "vm"
version = "0.1.2"

[dependencies.compiletest_rs]
version = "0.1.3"
optional = true

[dependencies.env_logger]
version = "0.3.3"
optional = true

[dependencies.linenoise-rust]
version = "0.2.0"
optional = true

[dependencies.lazy_static]
version = "0.2.0"
optional = true

[build-dependencies]
skeptic = "0.4"

[dev-dependencies]
skeptic = "0.4"

[features]
default = ["repl"]

repl = ["env_logger", "lazy_static", "linenoise-rust"]
test = ["gluon_vm/test", "gluon_check/test", "gluon_parser/test", "repl"]
nightly = ["compiletest_rs"]
test_nightly = ["test", "nightly"]
