[package]

name = "embed_lang"
version = "0.0.1"
authors = ["Markus <marwes91@gmail.com>"]


[lib]

name = "embed_lang"
path = "src/lib.rs"


[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies.log]
[dependencies.env_logger]
[dependencies.parser-combinators]
[dependencies.parser-combinators-language]
git = "https://github.com/Marwes/parser-combinators-language.git"

