[package]

name = "gluon"
version = "0.4.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]
build = "build.rs"

license = "MIT"

description = "A static, type inferred programming language for application embedding"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"
readme = "README.md"

[workspace]
members = ["c-api", "repl"]

[lib]

name = "gluon"
path = "src/lib.rs"

[dependencies]
gluon_base = { path = "base", version = "0.4.1" } # GLUON
gluon_check = { path = "check", version = "0.4.1" } # GLUON
gluon_parser = { path = "parser", version = "0.4.1" } # GLUON
gluon_vm = { path = "vm", version = "0.4.1" } # GLUON

log = "0.3.6"
quick-error = "1.0.0"
collect-mac = "0.1.0"
futures = "0.1.11"

# Binding crates
regex = { version = "0.2.1", optional = true }

# Crates used in testing Testing
compiletest_rs = { version = "0.2", optional = true }
skeptic = { version = "0.6", optional = true }

[build-dependencies]
skeptic = { version = "0.6", optional = true }

[dev-dependencies]
collect-mac = "0.1.0"
env_logger = "0.3.4"

hyper = { git = "https://github.com/hyperium/hyper", default-features = false, rev = "5c1cfa2bce93a57db2f720cd04436a5f92e80634" }
curl = "0.4.1"

[features]
default = ["regex"]

test = ["gluon_vm/test", "gluon_check/test", "gluon_parser/test"]
nightly = ["compiletest_rs"]
