[package]

name = "embed_lang"
version = "0.0.1"
authors = ["Markus <marwes91@gmail.com>"]


[lib]

name = "embed_lang"
path = "src/lib.rs"


[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
log = "0.3.6"
clap = "2.2.5"
quick-error = "1.0.0"

[dependencies.base]
path = "base"
[dependencies.parser]
path = "parser"
[dependencies.check]
path = "check"
[dependencies.vm]
path = "vm"

[dependencies.compiletest_rs]
version = "0.1.1"
optional = true

[dependencies.env_logger]
version = "0.3.3"
optional = true

[features]
test = ["vm/test", "check/test", "parser/test", "env_logger"]
nightly = ["compiletest_rs"]
test_nightly = ["vm/test", "check/test", "parser/test", "nightly"]
