[package]

name = "gluon"
version = "0.1.3"
authors = ["Markus <marwes91@gmail.com>"]
build = "build.rs"

license = "MIT"

description = "A static, type inferred programming langauge for application embedding"

repository = "https://github.com/Marwes/gluon"
documentation = "https://marwes.github.io/gluon/gluon/index.html"
readme = "README.md"

[workspace]
members = ["c-api"]

[lib]

name = "gluon"
path = "src/lib.rs"

[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
clap = "2.2.5"
compiletest_rs = { version = "0.2", optional = true }
env_logger = { version = "0.3.4", optional = true }
lazy_static = { version = "0.2.0", optional = true }
log = "0.3.6"
quick-error = "1.0.0"
rustyline = { version = "1.0.0", optional = true }
gluon_base = { path = "base", version = "0.1.3" }
gluon_check = { path = "check", version = "0.1.3" }
gluon_parser = { path = "parser", version = "0.1.2" }
gluon_vm = { path = "vm", version = "0.1.2" }

[build-dependencies]
skeptic = "0.6"

[dev-dependencies]
skeptic = "0.6"

[features]
default = ["repl"]

repl = ["env_logger", "lazy_static", "rustyline"]
test = ["gluon_vm/test", "gluon_check/test", "gluon_parser/test", "repl"]
nightly = ["compiletest_rs"]
