[package]

name = "gluon"
version = "0.2.2"
authors = ["Markus <marwes91@gmail.com>"]
build = "build.rs"

license = "MIT"

description = "A static, type inferred programming language for application embedding"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"
readme = "README.md"

[workspace]
members = ["c-api"]

[lib]

name = "gluon"
path = "src/lib.rs"

[[bin]]

name = "repl"
path = "src/main.rs"

[dependencies]
gluon_base = { path = "base", version = "0.2.2" }
gluon_check = { path = "check", version = "0.2.2" }
gluon_parser = { path = "parser", version = "0.2.2" }
gluon_vm = { path = "vm", version = "0.2.2" }

clap = "2.2.5"
log = "0.3.6"
quick-error = "1.0.0"

env_logger = { version = "0.3.4", optional = true }
lazy_static = { version = "0.2.0", optional = true }
rustyline = { version = "1.0.0", optional = true }

# Binding crates
regex = "0.2.1"

# Crates used in testing Testing
compiletest_rs = { version = "0.2", optional = true }
skeptic = { version = "0.6", optional = true }

[build-dependencies]
skeptic = { version = "0.6", optional = true }

[features]
default = ["repl"]

repl = ["env_logger", "lazy_static", "rustyline"]
test = ["gluon_vm/test", "gluon_check/test", "gluon_parser/test", "repl"]
nightly = ["compiletest_rs"]
