[package]
name = "vm"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies]
log = "0.3.5"
env_logger = "0.3.2"
quick-error = "0.2.2"

[dependencies.base]
path = "../base"

[dependencies.parser]
path = "../parser"
optional = true

[dependencies.check]
path = "../check"
optional = true

[features]
default = ["check", "parser"]
