[package]
name = "vm"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies]
log = "0.3.6"
quick-error = "1.0.0"

[dependencies.mopa]
git = "https://github.com/Marwes/mopa.git"

[dependencies.base]
path = "../base"

[dependencies.env_logger]
version = "0.3.3"
optional = true

[features]
test = ["env_logger"]
