[package]
name = "gluon_vm"
version = "0.4.2" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
quick-error = "1.1.0"
mopa = "0.2.2"
collect-mac = "0.1.0"
pretty = "0.2.0"
bitflags = "0.7.0"
itertools = "0.6.0"
futures = "0.1.0"
typed-arena = "1.2.0"
smallvec = "0.2.1"

gluon_base = { path = "../base", version = "0.4.2" } # GLUON
gluon_check = { path = "../check", version = "0.4.2" } # GLUON
gluon_parser = { path = "../parser", version = "0.4.2", optional = true } # GLUON

[build-dependencies]
lalrpop = { version = "0.13.1", optional = true }

[dev-dependencies]
lalrpop-util = "0.13.1"

[features]
test = ["env_logger", "lalrpop", "gluon_parser"]
