[package]
name = "gluon_vm"
version = "0.2.2"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
quick-error = "1.1.0"
mopa = "0.2.2"
collect-mac = "0.1.0"
pretty = "0.2.0"
bitflags = "0.7.0"
itertools = "0.5.6"
gluon_base = { path = "../base", version = "0.2.2" }
gluon_check = { path = "../check", version = "0.2.2" }

[features]
test = ["env_logger"]
