[package]
name = "gluon_vm"
version = "0.1.2"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

repository = "https://github.com/Marwes/gluon"
documentation = "https://marwes.github.io/gluon/gluon/index.html"

[dependencies]
log = "0.3.6"
quick-error = "1.0.0"
mopa = "0.2.2"

[dependencies.gluon_base]
path = "../base"
version = "0.1.2"

[dependencies.env_logger]
version = "0.3.3"
optional = true

[features]
test = ["env_logger"]
