[package]
name = "gluon_vm"
version = "0.12.0" # GLUON
authors = ["Markus <marwes91@gmail.com>"]
edition = "2018"
build = "build.rs"

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

homepage = "https://gluon-lang.org"
repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[badges]
travis-ci = { repository = "gluon-lang/gluon" }

[dependencies]
backtrace = "0.3"
bitflags = "1.0.0"
codespan = "0.3"
codespan-reporting = "0.3"
collect-mac = "0.1.0"
downcast-rs = "1"
difference = { version = "2", optional = true }
crossbeam-utils = "0.6"
frunk_core = "0.3"
futures = "0.1.0"
itertools = "0.8"
lalrpop-util = { version = "0.17", optional = true }
log = "0.4"
ordered-float = "1"
petgraph = "0.4"
pretty = "0.5"
quick-error = "1.1.0"
regex = { version = "1", optional = true }
smallvec = "0.6"
slab = "0.4"
typed-arena = "1.2.0"

serde = { version = "1.0.0", optional = true }
serde_json = { version = "1.0.0", optional = true }
serde_state = { version = "0.4.0", optional = true }
serde_derive = { version = "1.0.0", optional = true }
serde_derive_state = { version = "0.4.8", optional = true }

gluon_base = { path = "../base", version = "0.12.0" } # GLUON
gluon_check = { path = "../check", version = "0.12.0" } # GLUON
gluon_codegen = { path = "../codegen", version = "0.12.0" } # GLUON
gluon_parser = { path = "../parser", version = "0.12.0", optional = true } # GLUON

[build-dependencies]
lalrpop = { version = "0.17", optional = true }

[dev-dependencies]
difference = "2"
env_logger = "0.6"
pretty_assertions = "0.6"

# HACK Trick crates.io into letting letting this be published with a dependency on gluon
# (which requires gluon_vm to be published)
gluon = { path = "..", version = ">=0.9" }

lalrpop-util = "0.17"
regex = "1"
serde_json = "1.0.0"

gluon_parser = { path = "../parser", version = "0.12.0" } # GLUON

[features]
serialization = ["serde", "serde_state", "serde_derive", "serde_derive_state", "serde_json", "gluon_base/serialization", "codespan/serialization"]
test = ["difference", "lalrpop", "lalrpop-util", "regex", "serialization", "gluon_parser"]
