[package]
name = "vm"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies.quick-error]
version = "0.2.1"

[dependencies.base]
path = "../base"
[dependencies.parser]
path = "../parser"
[dependencies.check]
path = "../check"
