[package]
name = "gluon_vm"
version = "0.8.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
frunk_core = "0.2"
log = "0.4"
quick-error = "1.1.0"
mopa = "0.2.2"
collect-mac = "0.1.0"
pretty = "0.5"
bitflags = "1.0.0"
itertools = "0.7"
futures = "0.1.0"
typed-arena = "1.2.0"
smallvec = "0.6"
codespan = "0.1.1"

serde = { version = "1.0.0", optional = true }
serde_json = { version = "1.0.0", optional = true }
serde_state = { version = "0.4.0", optional = true }
serde_derive = { version = "1.0.0", optional = true }
serde_derive_state = { version = "0.4.0", optional = true }

gluon_base = { path = "../base", version = "0.8.1" } # GLUON
gluon_check = { path = "../check", version = "0.8.1" } # GLUON
gluon_codegen = { path = "../codegen", version = "0.8.1" } # GLUON

[build-dependencies]
lalrpop = { version = "0.15.1", optional = true }

[dev-dependencies]
env_logger = "0.5"
# HACK Trick crates.io into letting letting this be published with a dependency on gluon
# (which requires gluon_vm to be published)
gluon = { path = "..", version = "<0.9.0, >=0.7.0" }

lalrpop-util = "0.15.1"
regex = "0.2.0"
serde_json = "1.0.0"

gluon_parser = { path = "../parser", version = "0.8.1" } # GLUON

[features]
serialization = ["serde", "serde_state", "serde_derive", "serde_derive_state", "serde_json", "gluon_base/serialization", "codespan/serialization"]
test = ["lalrpop", "serialization"]
