[package]
name = "gluon_vm"
version = "0.5.0" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The virtual machine for executing the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
env_logger = { version = "0.3.4", optional = true }
frunk_core = "0.0.17"
log = "0.3.6"
quick-error = "1.1.0"
mopa = "0.2.2"
collect-mac = "0.1.0"
pretty = "0.3.1"
bitflags = "0.7.0"
itertools = "0.6.0"
futures = "0.1.0"
typed-arena = "1.2.0"
smallvec = "0.2.1"

serde = { git = "https://github.com/Marwes/serde", path = "serde", branch = "seeded_serialization", optional = true }
serde_derive = { git = "https://github.com/Marwes/serde", path = "serde_derive", branch = "seeded_serialization" }

gluon_base = { path = "../base", version = "0.5.0" } # GLUON
gluon_check = { path = "../check", version = "0.5.0" } # GLUON
gluon_parser = { path = "../parser", version = "0.5.0", optional = true } # GLUON

[build-dependencies]
lalrpop = { version = "0.13.1", optional = true }

[dev-dependencies]
# HACK Trick crates.io into letting letting this be published with a dependency on gluon
# (which requires gluon_vm to be published)
gluon = { path = "..", version = "<0.6.0, >=0.4.2" } # GLUON

lalrpop-util = "0.13.1"
regex = "0.2.0"
serde_json = { git = "https://github.com/Marwes/json" }

[features]
test = ["env_logger", "lalrpop", "gluon_parser"]
