[package]
name = "vm"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies.quick-error]
version = "0.2.2"

[dependencies.base]
path = "../base"

[dependencies.parser]
path = "../parser"
optional = true

[dependencies.check]
path = "../check"
optional = true

[features]
default = ["check", "parser"]
