[package]
name = "gluon_doc"
version = "0.13.1" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]
edition = "2018"

license = "MIT"

description = "The documentation generator for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
clap = "2.22.0"
env_logger = "0.7"
failure = { version = "0.1", features = ["backtrace"] }
futures = "0.3"
handlebars = "2"
itertools = "0.8"
lazy_static = "1"
log = "0.4"
opener = "0.4"
pretty = "0.10"
pulldown-cmark = "0.6"
rayon = "1"
regex = "1"
structopt = "0.3"
walkdir = "2"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

gluon = { version = "0.13.1", path = ".." } # GLUON
completion = { package = "gluon_completion", version = "0.13.1", path = "../completion" } # GLUON


[dev-dependencies]
cargo-deadlinks = "0.4.1"
