[package]
name = "gluon_repl"
version = "0.4.2" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]

license = "MIT"
description = "REPL for gluon. A static, type inferred programming language for application embedding"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon_repl"

[[bin]]
name = "gluon"

[dependencies]

gluon_vm = { version = "0.4.2", path = "../vm" } # GLUON
gluon = { version = "0.4.2", path = ".." } # GLUON

futures = "0.1.11"
clap = "2.22.0"
log = "0.3.6"
env_logger = { version = "0.3.4", optional = true }
lazy_static = "0.2.0"
rustyline = "1.0.0"

[features]
default = ["env_logger"]
