[package]
name = "gluon_repl"
version = "0.12.0" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]
edition = "2018"

license = "MIT"
description = "REPL for gluon. A static, type inferred programming language for application embedding"

homepage = "https://gluon-lang.org"
repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[badges]
travis-ci = { repository = "gluon-lang/gluon" }

[[bin]]
name = "gluon"
path = "src/main.rs"
doc = false

[dependencies]
gluon = { version = "0.12.0", path = "..", features = ["serialization"] } # GLUON
gluon_vm = { version = "0.12.0", path = "../vm", features = ["serialization"] } # GLUON
gluon_completion = { path = "../completion", version = "0.12.0" } # GLUON
gluon_codegen = { path = "../codegen", version = "0.12.0" } # GLUON
gluon_format = { version = "0.12.0", path = "../format" } # GLUON
gluon_doc = { version = "0.12.0", path = "../doc" } # GLUON

app_dirs = "1.0.0"
futures = "0.1.11"
futures-cpupool = "0.1"
tokio = "0.1"
tokio-signal = "0.2"
clap = "2.22.0"
structopt = "0.2"
structopt-derive = "0.2"
log = "0.4"
env_logger = { version = "0.6", optional = true }
lazy_static = "1"
rustyline = "5.0.1"
walkdir = "2"
codespan = "0.3"
codespan-reporting = "0.3"


serde = "1"
serde_derive = "1"

[target.'cfg(not(windows))'.dependencies]
ansi_term = "0.12"

[dev-dependencies]
pretty_assertions = "0.6"

[target.'cfg(unix)'.dev-dependencies]
rexpect = "0.3.0"

[features]
default = ["env_logger"]
test = []

