[package]
name = "gluon_repl"
version = "0.3.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[dependencies]

gluon_vm = { version = "0.3.0", path = "../vm" }
gluon = { version = "0.3.0", path = ".." }

futures = "0.1.11"
clap = "2.22.0"
log = "0.3.6"
env_logger = { version = "0.3.4", optional = true }
lazy_static = "0.2.0"
rustyline = "1.0.0"

[features]
default = ["env_logger"]
