[package]
name = "gluon_completion"
version = "0.5.0" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Auto-completion for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
gluon_base = { path = "../base", version = "0.5.0" } # GLUON
