[package]
name = "gluon_parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/Marwes/gluon"
documentation = "https://marwes.github.io/gluon/gluon/index.html"

[dependencies]
log = "0.3.6"

[dependencies.combine-language]
version = "=2.0.0-beta"

[dependencies.combine]
version = "=2.0.0-beta"

[dependencies.gluon_base]
path = "../base"

[dependencies.env_logger]
version = "0.3.3"
optional = true

[features]
test = ["env_logger"]
