[package]
name = "parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies]
combine = "^1.1.0"
combine-language = "0.9.0"
[dependencies.base]
path = "../base"
