[package]
name = "gluon_parser"
version = "0.2.1"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://gluon-lang.github.io/gluon/gluon/index.html"

[dependencies]
combine-language = "=2.0.0-beta4"
combine = "=2.0.0-beta3"
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
gluon_base = { path = "../base", version = "0.2.1" }

[features]
test = ["env_logger"]
