[package]
name = "gluon_parser"
version = "0.8.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
collect-mac = "0.1.0"
itertools = "0.7"
quick-error = "1.0.0"
lalrpop-util = "0.15.1"
log = "0.4"
pretty = "0.5"
gluon_base = { path = "../base", version = "0.8.1" } # GLUON
ordered-float = "0.5.0" # gluon_base
codespan = "0.1.1"
codespan-reporting = "0.1.1"

[dev-dependencies]
env_logger = "0.5"
difference = "2"
pretty_assertions = "0.5"

[build-dependencies]
lalrpop = "0.15.1"

[features]
test = []
