[package]
name = "gluon_parser"
version = "0.2.2"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
combine-language = "=2.0.0-beta4"
combine = "=2.0.0-beta3"
env_logger = { version = "0.3.4", optional = true }
quick-error = "1.0.0"
lalrpop = "0.12.0"
lalrpop-util = "0.12.0"
log = "0.3.6"
gluon_base = { path = "../base", version = "0.2.2" }
collect-mac = "0.1.0"

[build-dependencies]
lalrpop = "0.12.0"

[features]
test = ["env_logger"]
