[package]
name = "parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies.combine]
[dependencies.combine-language]
[dependencies.base]
path = "../base"
