[package]
name = "parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies]
log = "0.3.5"
env_logger = "0.3.2"

[dependencies.combine-language]
git = "https://github.com/Marwes/combine-language.git"
branch = "2.0.0"

[dependencies.combine]
git = "https://github.com/Marwes/combine.git"
branch = "2.0.0"
features = ["buffered_stream"]

[dependencies.base]
path = "../base"

[features]
test = []
