[package]
name = "parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies.parser-combinators]
[dependencies.parser-combinators-language]
git = "https://github.com/Marwes/parser-combinators-language"
[dependencies.base]
path = "../base"
