[package]
name = "parser"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies]
log = "0.3.5"
env_logger = "0.3.2"
combine-language = "0.9.0"

[dependencies.combine]
version = "^1.2.1"
features = ["buffered_stream"]

[dependencies.base]
path = "../base"
