[package]
name = "gluon_parser"
version = "0.1.2"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/Marwes/gluon"
documentation = "https://marwes.github.io/gluon/gluon/index.html"

[dependencies]
combine-language = "=2.0.0-beta2"
combine = "=2.0.0-beta"
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
gluon_base = { path = "../base", version = "0.1.2" }

[features]
test = ["env_logger"]
