[package]
name = "gluon_base"
version = "0.9.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Basic type definitions and functions for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.4"
quick-error = "1.0.0"
fnv = "1.0.3"
pretty = "0.5"
smallvec = "0.6"
collect-mac = "0.1.0"
anymap = "0.12.0"
itertools = "0.7"
ordered-float = "0.5.0"
codespan = "0.1.1"
codespan-reporting = "0.1.1"
either = "1"
stable_deref_trait = "1"

serde = { version = "1.0.0", features = ["rc"], optional = true }
serde_state = { version = "0.4.0", features = ["rc"], optional = true }
serde_derive = { version = "1.0.0", optional = true }
serde_derive_state = { version = "0.4.0", optional = true }

[dev-dependencies]
pretty_assertions = "0.5"

[features]
serialization = ["serde", "serde_state", "serde_derive", "serde_derive_state"]
