[package]
name = "gluon_base"
version = "0.5.0" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Basic type definitions and functions for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.3.6"
quick-error = "1.0.0"
fnv = "1.0.3"
pretty = "0.3.1"
smallvec = "0.2.1"
collect-mac = "0.1.0"
anymap = "0.12.0"
itertools = "0.5.6"

serde = { version = "1.0.0", features = ["rc"], optional = true }
serde_seed = { git = "https://github.com/Marwes/serde", path = "serde_seed", branch = "seeded_serialization", features = ["rc"], optional = true }
serde_derive = { version = "1.0.0", optional = true }
serde_derive_seed = { git = "https://github.com/Marwes/serde", path = "serde_derive_seed", branch = "seeded_serialization", optional = true }

[features]
serialization = ["serde", "serde_seed", "serde_derive", "serde_derive_seed"]
