[package]
name = "gluon_base"
version = "0.4.2" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Basic type definitions and functions for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.3.6"
quick-error = "1.0.0"
fnv = "1.0.3"
pretty = "0.2.0"
smallvec = "0.2.1"
collect-mac = "0.1.0"
itertools = "0.5.6"
