[package]
name = "base"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]


[dependencies.log]
[dependencies.env_logger]
[dependencies.unify]
path = "../../unify"

[dependencies.mopa]
git = "https://github.com/Marwes/mopa.git"
