[package]
name = "gluon_c-api"
version = "0.1.3"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies.gluon]
version = "0.1.3"
path = ".."

[dependencies.libc]
version = "0.2.0"

[features]
test = ["gluon/test"]
