[package]
name = "gluon_c-api"
version = "0.1.3"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.14"
gluon = { version = "0.1.3", path = ".." }

[features]
test = ["gluon/test"]
nightly = ["gluon/nightly"]
