name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    # Only run deployment on git tags
    - CURRENT_TAG=`git describe --exact-match --abbrev=0 --tags || true`
    - >
        if [[ $CURRENT_TAG != "" ]]; then
            export GIT_HASH=$(git rev-parse HEAD)
            sh scripts/before_deploy.sh
        fi
